---
- name: Add a new tenant
  cisco.mso.mso_tenant:
    host: "{{ inventory_hostname }}"
    username: "{{ user }}"
    password: "{{ pass }}"
    validate_certs: no
    tenant: "{{ item.mso.tenant }}"
    state: present
  delegate_to: localhost

- name: Add onprem site to tenant
  cisco.mso.mso_tenant_site:
    host: "{{ inventory_hostname }}"
    username: "{{ user }}"
    password: "{{ pass }}"
    validate_certs: no
    tenant: "{{ item.mso.tenant }}"
    site: "{{ item.onprem.name }}"
    state: present
  delegate_to: localhost

- name: Add AWS site to tenant
  cisco.mso.mso_tenant_site:
    host: "{{ inventory_hostname }}"
    username: "{{ user }}"
    password: "{{ pass }}"
    validate_certs: no
    tenant: "{{ item.mso.tenant }}"
    site: "{{ item.aws.name }}"
    cloud_account: "{{ item.aws.acct_id }}"
    aws_trusted: true
    state: present
  delegate_to: localhost
